{% set name = "wrapspawner" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wrapspawner-{{ version }}.tar.gz
  sha256: fe517b41c5ff834388c37cec69ab9277558746306b585801a0836b0632c45aca

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - jupyterhub >=2.2

test:
  imports:
    - wrapspawner
  commands:
    - pip check
  requires:
    - jupyterhub
    - pip
    - tornado

about:
  home: http://jupyter.org
  summary: 'Wrapspawner: A spawner for Jupyterhub to wrap other spawners and allow the user to choose among them.'
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/jupyterhub/wrapspawner

extra:
  recipe-maintainers:
    - opoplawski
